name: C/C++ CI
on: [push, pull_request]

jobs:
  build:
    name: Build MXE
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jonaski/strawberry-mxe2:latest
